# Generated by Django 2.2.5 on 2019-11-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='classes',
            field=models.IntegerField(choices=[(1, '全栈1班'), (1, '全栈2班')], default=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (1, '女')], default=1, verbose_name='性别'),
        ),
    ]
