# Generated by Django 2.2.5 on 2019-11-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20191117_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='classes',
            field=models.IntegerField(choices=[(1, '全栈1班'), (2, '全栈2班')], default=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
        ),
    ]
