# Generated by Django 2.2.5 on 2019-11-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20191117_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题信息')),
                ('status', models.IntegerField(choices=[(1, '在线'), (2, '离线')], verbose_name='状态信息')),
            ],
        ),
    ]
