# Generated by Django 2.2.5 on 2019-09-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20190928_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='icon',
            field=models.CharField(max_length=32, null=True, verbose_name='图标'),
        ),
    ]
