# Generated by Django 2.2.5 on 2019-10-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_permission_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='url别名'),
        ),
    ]
