# Generated by Django 2.2.5 on 2019-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='url别名'),
            preserve_default=False,
        ),
    ]
