# Generated by Django 2.2.5 on 2019-10-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20191002_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(default=1, max_length=32, verbose_name='图标'),
            preserve_default=False,
        ),
    ]
